name: ssX-cool-retro-term
version: '1.1.1'
summary: cool-retro-term is a cool and retro terminal emulator.
description: |
  cool-retro-term is a terminal emulator which mimics the look and feel
  of the old cathode tube screens. It has been designed to be eye-candy,
  customizable, and reasonably lightweight.
grade: stable
confinement: classic

base: core22

apps:
  cool-retro-term:
    command: bin/desktop-launch $SNAP/usr/bin/cool-retro-term
    desktop: usr/share/applications/cool-retro-term.desktop
    environment:
      QML2_IMPORT_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt6/qml

parts:
  desktop-qt6:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt6"]
    build-packages:
      - build-essential
      - qt6-qtbase-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt6gui6
      - libgdk-pixbuf2.0-0
      - libqt6svg6
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt6

  my-part:
    source: https://github.com/Swordfish90/cool-retro-term
    source-type: git
    plugin: qmake6
    after: [desktop-qt6]

    build-packages:
      - build-essential
      - qmlscene
      - qt6-qmake
      - qt6-default

    stage-packages:
      - qmlscene
      - qml-module-qtquick-controls-qt6
      - qml-module-qtquick2-qt6
      - qml-module-qtgraphicaleffects-qt6
      - qml-module-qtquick-dialogs-qt6
      - qml-module-qtquick-localstorage-qt6
      - qml-module-qtquick-window2-qt6
      - libgl1
      - qt6-declarative-dev-tools
      - qml-module-qtquick-extras-qt6
      - qml-module-qt-labs-settings-qt6
      - qml-module-qt-labs-folderlistmodel-qt6
