name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
permissions:
  contents: write
jobs:
  build-appimage:
    name: Build (Linux, AppImage)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install build deps
        run: |
          sudo apt update
          sudo apt install -y build-essential rsync wget libgl1-mesa-dev
          
      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.10.0
          dir: ..
          # Removed qt5compat to strip legacy dependencies
          modules: qtshadertools
          setup-python: false
          cache: true
          
      - name: Build ssX-cool-retro-term
        run: |
          # Build main app with link to updated libs
          ./scripts/build-appimage.sh
          
      - name: Collect artifact
        run: |
          mkdir -p release
          mv ./*.AppImage release/
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssX-cool-retro-term-appimage
          path: ./release/*

      - name: Publish rolling release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dirty
          name: Rolling Release
          prerelease: true
          files: ./release/*
